runlocal:
	python manage.py runserver 0.0.0.0:8000

migrations:
	python manage.py makemigrations

migrate:
	python manage.py migrate

check:
	python manage.py check

migrateall: check migrations migrate
