# Generated by Django 3.0.2 on 2020-01-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='admin', max_length=250, verbose_name='Автор'),
        ),
    ]
